### ISSUE TITLE
Build fails with confusing message if wget is not available

### ISSUE THREAD

**Issue by ionut-arm** [parallaxsecond/parsec-interface-rs#17]
Found by @paulhowardarm - if `wget` is not installed on the machine running a build of `parsec-interface-rs`, the build fails with a message saying something akin to `File or folder not found`, because it cannot find the tar archive pulled down by `wget`.

This should bomb out earlier, when running the `wget` command, but it doesn't seem to do that.

Seems somewhat related to #7

**Comment by hug-dev** [comment]
After we do #12 we can remove cross-compilation tests and replace `wget` and `tar` dependencies in the build crate by the the curl crate and flate2 and tar instead as told in #7.
