### ISSUE TITLE
Add ResponseCode for unimplemented operations/attributes

### ISSUE THREAD

**Issue by ionut-arm** [parallaxsecond/parsec-interface-rs#27]
Currently we return `PsaErrorNotSupported` when support for any of the attributes in the PSA spec is not implemented. This is misleading, as it cannot be differentiated between a truly unsupported parameter and one that isn't implemented yet by Parsec. I think we had a very brief discussion about this at some point and decided it was ok to do this but in retrospect maybe we should've added a separate error code.

Proposed name: `UnimplementedParameter`.

**Comment by hug-dev** [comment]
We could also set an operation or a parameter as `Unsupport` now but remove that later when we finally support it? For me "unsupported" does not totally mean that it will never be in the future :)

If you check the API page 36, about `PSA_ERROR_NOT_SUPPORTED`:
> The requested operation or a parameter is not supported by this implementation.

Well, that is true, this specific version of Parsec (compiled from this specific commit) does not support the operation.
I agree though that we need to be clear saying that some unsupported operations/parameters will be supported at some point in the future!

**Comment by ionut-arm** [comment]
Don't think we should be dissecting the meaning of "unsupported", as the spec doesn't really say if it's something that could change in the future or not. 

But yes, having some sort of "temporal" unsupported would be useful, especially when we'll have more providers and will implement functionality gradually (and, maybe, for some of them a part of the operations will simply by eternally unsupported).

**Comment by ionut-arm** [comment]
Is this still on our plans or should we just carry on with `PSA_ERROR_NOT_SUPPORTED`?

**Comment by hug-dev** [comment]
I still think that we are using `PsaErrorNotSupported` correctly when returning from operations that we are not supporting currently but might do in the future. Hence, I would be ok to carry one with that until something else happens.

**Comment by hug-dev** [comment]
Closing as we seemed to agree on that one.
