### ISSUE TITLE
Find a way to represent deprecated primitives

### ISSUE THREAD

**Issue by hug-dev** [parallaxsecond/parsec-interface-rs#33]
Some primitives are deprecated and should not be used by default.
Some mechanism should be added to prevent using it at runtime by default, unless an option is given.

**Comment by ionut-arm** [comment]
I would also add creating a static constant that would be accessible from the interface that stores the identifiers of deprecated algorithms (maybe even including the ones marked as deprecated, e.g. MD5).

**Comment by hug-dev** [comment]
Should be done with parallaxsecond/parsec#119
