### ISSUE TITLE
Rename ProviderID

### ISSUE THREAD

**Issue by ionut-arm** [parallaxsecond/parsec-interface-rs#36]
I have a feeling that the `ProviderID` isn't really named appropriately anymore. `Provider` would probably be a better name, as we use the enum to identify the type of provider we're refering to throughout the stack, not just for managing their IDs

**Comment by hug-dev** [comment]
Should we also with this issue, refactor the `ProviderID` type completely? I think we agreed that in the future, if we have multiple providers of the same type, this won't work anymore. Maybe `ProviderID` should just be a new type composed of a value + a type?

**Comment by ionut-arm** [comment]
I think this will be painful to change because a lot of things depend on a clear mapping from `ProviderID` to provider type, but that's more of an incentive to do that sooner before we hardcode even more stuff to that assumption

**Comment by hug-dev** [comment]
Should think about that in parallaxsecond/parsec-book#83

**Comment by ionut-arm** [comment]
> Should think about that in [parallaxsecond/parsec-book#83](https://github.com/parallaxsecond/parsec-book/issues/83)

Hmm, that's true, I think the stability issue here is related to the interface of the client - how do users specify they want "That particular provider!". At the moment the list is static, in the future it could change. I've written a short comment on the issue above, will close this and raise a more clear issue once we get to it.
