### ISSUE TITLE
Update to PSA Crypto API 1.0.0

### ISSUE THREAD

**Issue by ionut-arm** [parallaxsecond/parsec-interface-rs#4]
At the moment we're using an old version of the PSA Crypto API spec which has since been updated. 
https://github.com/ARMmbed/mbed-crypto/raw/psa-crypto-api/docs/PSA_Cryptography_API_Specification.pdf

Changes that are needed for our current set of operations include:
* Introducing a Diffie-Hellman group enum (similar to elliptic curves)
* Introducing a `permit_copy` flag for keys
* Removing `key_lifetime` from all operations that use it (although with what this will be replaced remains TBD)

Given that we've not yet released a stable version, we can directly modify the existing contracts, however this should be some food for thought for us - if we were to update the key attributes structure (in the proto contracts) in the future, we'll have to create new contracts for every operation that uses any key attribute in its definition.

**Comment by hug-dev** [comment]
The PSA Crypto spec version 1.0.0 is now out! Available for download [here](https://developer.arm.com/-/media/Files/pdf/PlatformSecurityArchitecture/Implement/IHI0086-PSA_Cryptography_API-1.0.0.pdf)
Should we include that one in the "Parsec production ready" milestone?

**Comment by ionut-arm** [comment]
I'm dreading the day when we'll have to upgrade the PSA crypto spec 😱

**Comment by hug-dev** [comment]
We should also check that our `ResponseStatus` codes corresponding to the PSA Crypto API ones are still correct.
