### ISSUE TITLE
Add body type getter in Convert trait

### ISSUE THREAD

**Issue by ionut-arm** [parallaxsecond/parsec-interface-rs#40]
Request and response bodies are converted to and from raw byte format using code specific to each body type that we support. In order to have modularity, though, converters are handled through a `Convert` trait. However, in order to correctly compose requests and responses, you explicitly need to know the `BodyType` that you're using. 

Because the components doing the body conversion usually also create the request or response header (be it either in the service or in the client), it makes sense to be able to retrieve the `BodyType` straight from the converter, minimizing the risk of the two (body encoding type and encoding type identifier in the header) becoming inconsistent.

**Comment by hug-dev** [comment]
That's a good point! It will also simplify the `BackEndHandler` in the service to not duplicate that information.
