### ISSUE TITLE
Create conversion method from TryFromIntError for ResponseStatus

### ISSUE THREAD

**Issue by ionut-arm** [parallaxsecond/parsec-interface-rs#53]
There are a lot of points in the service where conversions occur between integer types and some require unwrapping of the result as they relate to usize being used in a context where its size might be lower than we expect to support. Nevertheless, it would be good to modify these `unwrap` calls to a conversion to `ResponseStatus` and return the error.

These `try_from` conversions return https://doc.rust-lang.org/std/num/struct.TryFromIntError.html . Logging the error and simply returning `GenericError` seems like a sensible approach.

**Comment by hug-dev** [comment]
Maybe that can also be extended for the other `unwrap` or `expect` that we do on things that return an error but we expect to never fail, like:
* parsing the UUID
* getting the `OUT_DIR` environment variable

Only if those above would not change the prototype of methods I guess.
