### ISSUE TITLE
Audit response status code for information disclosure

### ISSUE THREAD

**Issue by hug-dev** [parallaxsecond/parsec-interface-rs#59]
Mitigation one of our [threat model](https://parallaxsecond.github.io/parsec-book/threat_model/threat_model.html#mitigations) says:

> Response statuses are audited to not give too much information to the client.

This issue is to investigate and make sure this is the case.

**Comment by ionut-arm** [comment]
By this I assume we mean only the non-PSA response codes. Also, it only means the response code alone, since we send back no data about the failure, just a number.

**Comment by hug-dev** [comment]
The service specific response codes are defined [here](https://parallaxsecond.github.io/parsec-book/parsec_client/status_codes.html#service-internal-response-status-codes). Having looked at it, the information they contain is either public or not confidential.
