### ISSUE TITLE
Implement Deref on RequestBody and ResponseBody

### ISSUE THREAD

**Issue by ionut-arm** [parallaxsecond/parsec-interface-rs#61]
Currently the body and authentication fields of requests and responses are just wrappers around byte buffers, however they do not appear so from their interface - ideally they should implement `Deref` and `DerefMut` which would allow users to treat them as plain old vectors.

Whether this is a good idea should be assessed, though, as for some types we might want to limit what operations are possible, for safety reasons.

Another good idea is to verify which conversions are implemented and which should be, ideally.

**Comment by hug-dev** [comment]
Agree for the body part but maybe not for the auth one as this is a secret and we want to control where it's leaked. We currnetly use `SecretVec` for that.
